### PR TITLE
Add some support methods for `Matrix`

### PR DESCRIPTION
**Pull request by jasonhotsauce**
* `Matrix` confirms to `Equatable`
* Add `subscript` supports return specific rows or columns
* Add support for scaling matrix by row or by column.
* Make `pow` supports applying to every elements in vector.

### CODE REVIEW

**Comment by jasonhotsauce** [comment]
@rfdickerson Can you please review this PR?

**Comment by jasonhotsauce** [comment]
Added some tests for the methods I created to make sure I didn't mess up this time. I think having Travis is a good idea to prevent mistakes.

**Comment by jasonhotsauce** [comment]
Hi, @rfdickerson , Do you have time to take a look at this?

**Comment by rfdickerson** [comment]
I believe this PR currently has some merge conflicts that need to be resolved. I like the features added to Matrix, though.

**Comment by jasonhotsauce** [comment]
Sure. I will resolve it and debase to master.

**Comment by jasonhotsauce** [comment]
@rfdickerson resolved conflicts and passed all tests.

**Pull request merged**
