### PR TITLE
Changed element-wise operators from + to .+ to resolve #58

### LINKED ISSUE #58: Importing Surge changes the behavior of + between array
Hi,

In files where Surge is imported, the behavior of the + operator between arrays is modified by the library.

Normal Swift behavior : concatenation
```swift
[1.0, 2.0, 3.0] + [1.0, 2.0, 3.0] // [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
```

Surge overloaded behavior : addition
```swift
[1.0, 2.0, 3.0] + [1.0, 2.0, 3.0] // [2.0, 4.0, 6.0]
```

I don't know if it's a feature or a bug, but it took me 2 hours to find the problem after importing Surge into my code. So maybe it's a bad idea to overload this operator.

What do you think about removing this feature?

### PR DESCRIPTION
**Pull request by morpheby**
As suggested in #58, all element-wise operations on array changed from `+`-style to `.+`-style.

List of changed operators:

* `+` –> `.+`
* `+=` –> `.+=`
* `-` –> `.-`
* `-=` –> `.-=`
* `/` –> `./`
* `/=` –> `./=`
* `*` –> `.*`
* `*=` –> `.*=`
* `%` –> `.%`
* `%=` –> `.%=`

### CODE REVIEW

**Comment by alejandro-isaza** [comment]
@mattt what do you think about this? My main concern is that this will break everyone's code. Should we have both version and mark the non-dot ones as deprecated?

**Comment by mattt** [comment]
@alejandro-isaza I think this is a good change. Spelling-wise, there's strong precedent for the use of dot-prefixed element-wise operators in [MATLAB](https://www.mathworks.com/help/matlab/matlab_prog/array-vs-matrix-operations.html).

**Comment by mattt** [comment]
I don't think there's a way to deprecate the old operators, since they're overloads of existing Swift Standard Library operators. We should bump a major or minor version and note the behavior difference in a Changelog / README / documentation.

The only change I'd like to see is to remove f270630 from this PR. It doesn't seem to be related to renaming operators, and should be evaluated separately.

**Comment by alejandro-isaza** [comment]
@morpheby can you rebase to remove that commit? I'll merge when you do that.

**Pull request merged**
