### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by madbat**
I’ve done the minimum set of changes to make Surge compile with Swift 2.0

### CODE REVIEW

**Comment by Boggartfly** [comment]
Hey @mattt , Thanks for making this fantastic library for us! Now can you please consider to merge this pull request into the main repo? I'm a HAM radio operator considering building SDR software for my VUSDR(Peaberry clone). Original maker was @AE9RB

**Comment by jackywang135** [comment]
Any news on if and when this project will get updated to 2.0?

**Comment by harlanhaskins** [comment]
@Boggartfly In the meantime, use this fork in your podfile. 

```ruby
pod 'Surge', :git => 'https://github.com/madbat/Surge.git', :branch => 'master'
```

**Comment by bielikb** [comment]
hey @mattt, will you update Surge in any close time? #swift2support

**Pull request closed without merging**
